char tela_principal(void);
char tela_submenu_ingredientes(void);
char tela_submenu_modopreparo(void);
char tela_receitas(void);
char tela_menu_chefe(void);
char tela_menu_cardapio(void);
char tela_menu_relatorios(void);
char tela_informacoes(void);
void moduloReceita(void);